% This script demonstrates how to run reconstructions based on parameters and datasets described in
% an excel file. Specifically the script allows the creation of the all the reconstructions referred
% to and analyzed within the text.
% 
% Many code blocks below are commented out. It is advizable to run these blocks one by one. 
% Furthermore, the blocks and parameters might need to be adjusted for your architecture. The first
% 'quick test' block, requires 1 GPU, whereas the latter blocks require computers with 3 GPUs 
% (or possibly 3 virtual GPUs). To modify a block to just run on one GPU change for example 
% 'exec_char','rst',...  to 'exec_char','r',... . The characters r,s,t in this example relate to 
% datasets and recipes in the Excel sheet. If 'rst' is specified, datasets r, s, t with 
% related recipes r, s, and t run in parallel. If just 'r' is specified, then only dataset 'r' is 
% processed with the related recipes 'r'.
% 
% 
% 
% *******************************************************************
% Author & Copyright: Arthur M. Blackburn
% Year              : 2024
% Contact           : ablackbu@uvic.ca / arthur.blackburn@gmail.com
% Citation and Attribution: If possible, please cite the related publication
% given at https://github.com/ArthurBlackburn/PtychoRunner.
% Otherwise, thanks would be appreciated if you find this code useful.
% 
% *******************************************************************
% Put a dump of key parameters and the contents of this file to the screen or file output log in 
% nodisplaymode so we know exactly what called that run etc. 
% This is useful for slurm or other batch runs, but is not strictly necessary.
calling_name = mfilename('fullpath');
fprintf(['Execution of m-file: %s ,\nStarted at %s ,\n',...
         'Called from %s ,\nExecuting code:\n'],...
    calling_name,...
    datetime("now"),...
    sprintf('job name %s with job ID %s\n',getenv('SLURM_JOB_NAME'),getenv('SLURM_JOB_ID')));
eval(sprintf('type ''%s\''',calling_name));

% Put the path to your xls file here. It is recommended to make a copy of the xls file in
% \Runner\TestScripts and place it another directory where you keep records of the reconstructions.
% The below is just an example:
dataset_location = 'D:\YourProjects\MyReconstructionRecords';

% -- Run parameters are below here: Uncomment out the runs you want to do depending on your platform 
% i.e., remove / move %{ and %} etc.

% 1) A quickish test run to see if things are working. This should take 1 - 2 minutes to run on an
% 2015 GPU, and less on a more modern one. It should use less than 2GB on your GPU.
% %{
RunReconN(struct(...
'datasets_path',dataset_location,...
'ExcelFileName','DataAndRecipes.xls',...
'ExcelShortName','Demo01NC',...
'ExperimentSheet','Datasets',...
'RecipeSheet','Recipes',...
'RunOnSamples','synth',...
'exec_char','y',...
'FileSaveOverride',struct('search','Rx',...
                          'replace_fmt','R_%02.0f',...
                          'replace_num',1)));


%{
% 2) Synthetic data at conditions very similar to those used in the Au on MoS2 reconstruction
RunReconN(struct(...
'datasets_path',dataset_location,...
'ExcelFileName','DataAndRecipes.xls',...
'ExcelShortName','Demo01NC',...
'ExperimentSheet','Datasets',...
'RecipeSheet','Recipes',...
'RunOnSamples','synth',...
'exec_char','rst',...
'FileSaveOverride',struct('search','Rx',...
                          'replace_fmt','R_%02.0f',...
                          'replace_num',1)));

% 3) Synthetic data at conditions very similar to those used in the Au on amorphous carbon (aC) reconstruction
RunReconN(struct(...
'datasets_path',dataset_location,...
'ExcelFileName','DataAndRecipes.xls',...
'ExcelShortName','Demo01NC',...
'ExperimentSheet','Datasets',...
'RecipeSheet','Recipes',...
'RunOnSamples','synth',...
'exec_char','uvw',...
'FileSaveOverride',struct('search','Rx',...
                          'replace_fmt','R_%02.0f',...
                          'replace_num',1)));


% 4) Experimental data from Au on Amorphous carbon (aC) - with no distortion correction
RunReconN(struct(...
'datasets_path',dataset_location,...
'ExcelFileName','DataAndRecipes.xls',...
'ExcelShortName','Demo01NC',...
'ExperimentSheet','Datasets',...
'RecipeSheet','Recipes',...
'RunOnSamples','experi',...
'exec_char','abc',...
'FileSaveOverride',struct('search','Rx',...
                          'replace_fmt','R_%02.0f',...
                          'replace_num',1)));

% 5) Experimental data from Au on Amorphous carbon (aC) - after first round of distortion correction
RunReconN(struct(...
'datasets_path',dataset_location,...
'ExcelFileName','DataAndRecipes.xls',...
'ExcelShortName','Demo01NC',...
'ExperimentSheet','Datasets',...
'RecipeSheet','Recipes',...
'RunOnSamples','experi',...
'exec_char','def',...
'FileSaveOverride',struct('search','Rx',...
                          'replace_fmt','R_%02.0f',...
                          'replace_num',1)));

% 6) Experimental data from Au on Amorphous carbon (aC) -  after second (and final) round of distortion correction
RunReconN(struct(...
'datasets_path',dataset_location,...
'ExcelFileName','DataAndRecipes.xls',...
'ExcelShortName','Demo01NC',...
'ExperimentSheet','Datasets',...
'RecipeSheet','Recipes',...
'RunOnSamples','experi',...
'exec_char','ghk',...
'FileSaveOverride',struct('search','Rx',...
                          'replace_fmt','R_%02.0f',...
                          'replace_num',1)));

% 7) Experimental data from Gold Islands on MoS2 (using distortion corrected data)
RunReconN(struct(...
'datasets_path',dataset_location,...
'ExcelFileName','DataAndRecipes.xls',...
'ExcelShortName','Demo01NC',...
'ExperimentSheet','Datasets',...
'RecipeSheet','Recipes',...
'RunOnSamples','experi',...
'exec_char','q',...
'FileSaveOverride',struct('search','Rx',...
                          'replace_fmt','R_%02.0f',...
                          'replace_num',1)));


% Simulated from a hexagonal frustrum gold island on 5 layers of MoS2, where the entire system is tilted slightly to best match our experimentally determined tilt angle
RunReconN(struct(...
'datasets_path',dataset_location,...
'ExcelFileName','DataAndRecipes.xls',...
'ExcelShortName','Demo01NC',...
'ExperimentSheet','Datasets',...
'RecipeSheet','Recipes',...
'RunOnSamples','synth',...
'exec_char','m',...
'FileSaveOverride',struct('search','Rx',...
                          'replace_fmt','R_%02.0f',...
                          'replace_num',1)));
%}



